# Generated by Django 3.0.2 on 2020-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vind je dit leuk?', models.BooleanField(verbose_name='q1')),
                ('Waar ga je heen?', models.BooleanField(verbose_name='q2')),
            ],
        ),
    ]
