# Generated by Django 3.0.2 on 2020-01-16 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=280)),
                ('url', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.BooleanField(help_text='Does the tweet or the linked source have anything to do with the societal discussion around vaccines? (If not, continue to next tweet)', verbose_name='q1')),
                ('q2', models.BooleanField(help_text='Is the source that is shared in the tweet still available? (If not, continue to next tweet)', verbose_name='q2')),
                ('q3', models.BooleanField(help_text='Does the tweet contain any text next to the link?', verbose_name='q3')),
                ('q4', models.BooleanField(help_text='Does the tweet contain any text next to the title of the shared link?', verbose_name='q4')),
                ('q5', models.IntegerField(choices=[(0, 'The source does not contain a discernible opinion on vaccines'), (1, 'Strongly Against'), (2, 'Against'), (3, 'Neutral'), (4, 'In Favor'), (5, 'Strongly In Favor')], help_text='To what extent would you describe the source as in favor or against the use of vaccines?', verbose_name='q5')),
                ('q6', models.IntegerField(choices=[(0, 'The tweet does not contain a discernible opinion on vaccines'), (1, 'Strongly Against'), (2, 'Against'), (3, 'Neutral'), (4, 'In Favor'), (5, 'Strongly In Favor')], help_text='To what extent would you describe the tweet as in favor or against the use of vaccines?', verbose_name='q6')),
                ('q7', models.IntegerField(choices=[(0, 'The tweet does not contain a discernible opinion towards the source'), (1, 'Strongly disagrees'), (2, 'disagrees'), (3, 'Neutral'), (4, 'Agrees'), (5, 'Strongly agrees')], help_text='To what extent does the tweet (dis)agreement with the source?', verbose_name='q7')),
                ('q8', models.IntegerField(choices=[(0, 'The tweet does not contain a discernible opinion towards the source'), (1, 'Very Negative'), (2, 'Negative'), (3, 'Neutral'), (4, 'Positive'), (5, 'Very positive')], help_text='To what extent would you describe the tweet as positive or negative towards the source?', verbose_name='q8')),
                ('q9', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='On a scale from 1 to 5, to what extent does the tweet express feelings of enthusiasm?', verbose_name='q9')),
                ('q10', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='On a scale from 1 to 5, to what extent does the tweet express feelings of anger?', verbose_name='q10')),
                ('q11', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='On a scale from 1 to 5, to what extent does the tweet express feelings of fear?', verbose_name='q11')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alacode.Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tweet', 'user')},
            },
        ),
    ]
