# Generated by Django 3.0.2 on 2020-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alacode', '0002_auto_20200116_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='q10',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='Does the tweet express feelings of anger?', verbose_name='q10'),
        ),
        migrations.AlterField(
            model_name='code',
            name='q11',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='Does the tweet express feelings of fear?', verbose_name='q11'),
        ),
        migrations.AlterField(
            model_name='code',
            name='q12',
            field=models.CharField(default='no notes', help_text='Notes', max_length=500, verbose_name='q12'),
        ),
        migrations.AlterField(
            model_name='code',
            name='q9',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='Does the tweet express feelings of enthusiasm?', verbose_name='q9'),
        ),
    ]
